Fix info handler not returning numberOfPoints in Retentions
go-graphite/go-carbon pull request #233
Opened 2018-05-02 16:51 UTC by gksinghjsr

Due to incomaptible type conversion between retention protocols v2 and v3, numberOfPoints was becoming 0. 
https://play.golang.org/p/zUJrIyB9792

Fix uses retention of first metric to construct v2 response, rather than trying to convert v3 to v2.

2018-05-02 17:07 UTC, gksinghjsr commented
Is there any reason why we were returning protoV2Format and protoV3Format as protoV2Format? If there are any concerns around this, then the pull request will need a change and go back to clubbing the two cases together, with the only change being related to RetentionV2 being used to construct the response.

2018-05-03 09:53 UTC, gksinghjsr commented
@Civil any ideas around grouping of protoV2Format and protoV3Format together?

2018-05-04 19:57 UTC, Civil commented on carbonserver/info.go
>  		var r protov3.MetricsInfoResponse
Shouldn't it be protov2.MetricsInfoResponse here?

2018-05-04 19:58 UTC, Civil commented on carbonserver/info.go
>  		var r protov3.MetricsInfoResponse
Ah sorry, my fault, it's ok.

2018-05-04 19:59 UTC, Civil commented
@gksinghjsr what do you mean by "Is there any reason why we were returning protoV2Format and protoV3Format as protoV2Format" ?

For me current PR seems to be ok.

2018-05-04 20:01 UTC, Civil requested changes

2018-05-04 20:01 UTC, Civil commented on carbonserver/info.go
> +			//only one metric is enough - first metric
ProtoV2 doens't support multiple metrics in response here.

I also think it makes more sense to move this sutff to `case protoV2Format`, just grab the first response from protoV3 structure and convert it to protoV2

2018-05-07 10:15 UTC, gksinghjsr commented
Whether metric is read from the form, or in case of protoV3, from body request, it will be an array, and it needs to be outside as even for protoV2, it is getting populated when the whisper files are being read. The protoV3 response is also the one being used as deafult to convert to json.

2018-05-07 20:15 UTC, Civil commented
I mean there is no need to populate protoV2 responses all the time. I think it's better to convert protoV3 to protoV2 on demand.
In that case we'll spend more time doing protov2 requests, but when people migrate to protov3 it won't do unnecessary work.

2018-05-25 09:32 UTC, gksinghjsr commented
@Civil Added a check to make sure that we update the retentions only in case the format is protoV2.

2018-05-25 10:53 UTC, merged